### refreshToken.http

@baseUrl = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

### ================== RUTAS SIN AUTENTICACIÓN ==================

### Obtener todos los refresh tokens
GET {{baseUrl}}/refresk-token

### ================== RUTAS CON AUTENTICACIÓN ==================