### resource.http

@baseUrl = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

### ================== RUTAS SIN AUTENTICACIÓN ==================

### Obtener todos los recursos
GET {{baseUrl}}/api/resources

### Obtener recurso por ID
GET {{baseUrl}}/api/resources/1

### Crear un nuevo recurso
POST {{baseUrl}}/api/resources
Content-Type: application/json

{
  "path": "/api/appointments/:id/complete",
  "method": "patch",
  "is_active": "ACTIVE"
}

### Actualizar un recurso
PATCH {{baseUrl}}/api/resources/1
Content-Type: application/json

{
  "path": "/api/clientes/:id",
  "method": "GET",
  "is_active": "ACTIVE"
}

### Eliminar un recurso físicamente
DELETE {{baseUrl}}/api/resources/1

### Eliminar un recurso lógicamente
DELETE {{baseUrl}}/api/resources/1/logic

### ================== RUTAS CON AUTENTICACIÓN ==================