### user.http

@baseUrl = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

### Esto es solo como ejemplo academico, dado que este modelo lo debemos manejar posteriormente con Auth
### ================== RUTAS SIN AUTENTICACIÓN ==================

### Obtener todos los usuarios
GET {{baseUrl}}/api/users

### Crear usuario (usando el mismo endpoint)
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "username": "yair",
  "email": "yair@gmail.com",
  "password": "123456",
  "is_active": "ACTIVE",
  "avatar": "avatar.jpg"
}

### ================== RUTAS CON AUTENTICACIÓN ==================