@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTc2MDA2MDU1NywiZXhwIjoxNzYwMDYxMTU3fQ.l9kxHGraKffDkcOLHMmaVa12iOQKdrhZHrNnP6wb6dA
@baseUrl = http://localhost:4000

### ================== RUTAS SIN AUTENTICACIÓN ==================

### Obtener todos los laboratorios (SIN token)
GET {{baseUrl}}/api/laboratories/public

### Obtener laboratorio por ID (SIN token)
GET {{baseUrl}}/api/laboratories/public/1

### Crear un nuevo laboratorio (SIN token)
POST {{baseUrl}}/api/laboratories/public
Content-Type: application/json

{
  "pet_id": 9,
  "test_name": "Hemograma",
  "result": "Normal",
  "date": "2025-10-25T10:00:00.000Z",
  "status": "ACTIVE"
}

### Actualizar un laboratorio (SIN token)
PATCH {{baseUrl}}/api/laboratories/public/2
Content-Type: application/json

{
  "pet_id": 1,
  "test_name": "Hemograma Actualizado",
  "result": "Leve alteración",
  "date": "2025-10-25T12:00:00.000Z",
  "status": "ACTIVE"
}

### Eliminar un laboratorio físicamente (SIN token)
DELETE {{baseUrl}}/api/laboratories/public/1

### Desactivar un laboratorio (cambiar status a INACTIVE) (SIN token)
PATCH {{baseUrl}}/api/laboratories/public/2/deactivate

### ================== RUTAS CON AUTENTICACIÓN ==================

### Obtener todos los laboratorios (CON token)
GET {{baseUrl}}/api/laboratories
Authorization: Bearer {{token}}

### Obtener laboratorio por ID (CON token)
GET {{baseUrl}}/api/laboratories/1
Authorization: Bearer {{token}}

### Crear un nuevo laboratorio (CON token)
POST {{baseUrl}}/api/laboratories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "pet_id": 2,
  "test_name": "Examen de orina",
  "result": "Leve infección",
  "date": "2025-10-26T09:30:00.000Z",
  "status": "ACTIVE"
}

### Actualizar un laboratorio (CON token)
PATCH {{baseUrl}}/api/laboratories/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "pet_id": 2,
  "test_name": "Examen de orina Actualizado",
  "result": "Normalizado",
  "date": "2025-10-26T11:00:00.000Z",
  "status": "ACTIVE"
}

### Eliminar un laboratorio físicamente (CON token)
DELETE {{baseUrl}}/api/laboratories/1
Authorization: Bearer {{token}}

### Desactivar un laboratorio (cambiar status a INACTIVE) (CON token)
PATCH {{baseUrl}}/api/laboratories/1/deactivate
Authorization: Bearer {{token}}
